### ISSUE TITLE
Dead person with Birth Place - Does not display birth place.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#108]
When a search for a place of birth is executed, some results return that do not display the place of birth under the persons details.
In the GEDCOM file, it is clearly indicated that the place of birth is indeed Moscow, however, in the details section a birth place is not displayed. It isn't displayed on the result card, either.

Reproduce:
1. Search for Birth Place: Moscow
2. Scroll down and find the person "Svetlana Lifshittz"
3. Expand person details.

Result:
Place of birth is not indicated, although in the gedcom one can clearly see that it exists:

1 NAME svetlana /lifshittz/
2 GIVN svetlana
2 SURN lifshittz
2 _MARNM chikovskaya
1 SEX F
1 BIRT
2 PLAC moscow
1 DEAT Y

**Comment by TheGrandVizier** [comment]
Another example from the same tree:
1 NAME marik /chikovskya/
2 GIVN marik
2 SURN chikovskya
1 SEX M
1 BIRT
2 PLAC moscow
1 DEAT Y
1 BURI
2 PLAC moscow

**Comment by OriHoch** [comment]
![image](http://dontwannahearit.com/wp-content/uploads/2009/11/the-fun-never-ends-300x168.jpg)

**Comment by OriHoch** [comment]
there is a mis-match between frontend and backend:

in the [api](http://api.dbs.bh.org.il/v1/item/person_11433%3B0.I500115) there are the following fields for birth place:
* `BIRT_PLAC_lc: "moscow"`
* `birth_place: "moscow"`

in the front-end the field that is used in person details is "BIRTH_PLAC"

#### TODO
* find out what changed / why this bug happes (did it work before? is is something specific in this person?)
* ensure a consistent field used between back and front, I guess it should be the "birth_place" field - need to make sure it is always populated by migration process / API and used by front-end

**Comment by OriHoch** [comment]
in the search results the place is displayed, meaning that it has different logic then in person details - need to ensure consistent logic there as well (use the "birth_place" field)

![image](https://cloud.githubusercontent.com/assets/1198854/23353375/d3abd366-fcd4-11e6-8dc7-b4033b4ef6c6.png)

**Comment by OriHoch** [comment]
looks like the bug was introduced in this [commit](https://github.com/Beit-Hatfutsot/dbs-back/commit/2d3c1de9bd92f8f99db4bcb357098b590342e6ff) - it replaced the gedcom BIRTH_PLAC with "birth_place" and removed BIRTH_PLAC attribute which frontend was using

**Comment by OriHoch** [comment]
currently both search results and item details backend API calls go through clean_person function which ensures `birth_place` attribute exists

now the fix should be done on frontend - to ensure all places use the birth_place attribute

**Comment by OriHoch** [comment]
tested on production (http://dbs.bh.org.il/he/person/11433/0/I500115), looks good
