### ISSUE TITLE
Setup Public Instagram Feed in Lobby

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#109]
We want to set up a public slideshow on a big monitor to show photos from our instagram feed.

![insetush](https://cloud.githubusercontent.com/assets/15191989/23357044/d0e220d0-fce4-11e6-925e-3179370fa57c.jpg)
![hadmaya](https://cloud.githubusercontent.com/assets/15191989/23357049/d5621660-fce4-11e6-8ec3-ca7597c09656.png)

**Comment by TheGrandVizier** [comment]
Deployed!

**Comment by OriHoch** [comment]
pics or it didn't happen

**Comment by TheGrandVizier** [comment]
you missed it, it was in BH email 🗡

**Comment by OriHoch** [comment]
![image](https://cloud.githubusercontent.com/assets/1198854/23844596/e742142e-07cb-11e7-9612-3b2bdf3ab426.png)
![image](https://cloud.githubusercontent.com/assets/1198854/23844599/ec90c4de-07cb-11e7-8d08-92afddf6c9a6.png)
![image](https://cloud.githubusercontent.com/assets/1198854/23844601/f26b9a1e-07cb-11e7-9e9c-50f3434c3f73.png)
