### ISSUE TITLE
After migrating a fresh tree, we have persons with no slugs

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#115]
To reproduce, migrate a new tree, then search for it using its tree number. click on any of the results and you will get an empty person display page.
Seems like the server is returning  404 for the person and the db holds the persons but with a null `Slug`

**Comment by daonb** [comment]
A workaround is to run the migration again

**Comment by TheGrandVizier** [comment]
Test with tree 12389 (noga lev ari)

**Comment by nuritgazit** [comment]
only in Hebrew:
נגה לב ארי

**Comment by OriHoch** [comment]
the tree is now updated in production - 
http://dbs.bh.org.il/person/12389/0/I1
