### ISSUE TITLE
General Search Filters for Persons (ftrees)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#119]
In the Persons tab of general search, provide filters for filtering persons and trees.

Should support the following filters being applied to a provided result-set.
Most of them should have an operator, indicated in brackets:

- First name 
- Last name (Exact, Starts with, Sounds like)
- Sex (Male, Female, Nevermind)
- Place of birth (Exact, Starts with, Sounds like)
- Place of marriage (Exact, Starts with, Sounds like)
- Place of death (Exact, Starts with, Sounds like)
- Year of birth (Exact, +/-1 year, +/-2 years, +/-3 years)
- Year of marriage (Exact, +/-1 year, +/-2 years, +/-3 years)
- Year of death (Exact, +/-1 year, +/-2 years, +/-3 years)
- Tree number

Only one operator can be selected at a time, per filter.
Default is Exact, except for years, where the default is +/-2 years.

Frontend: https://github.com/Beit-Hatfutsot/dbs-front/issues/280

**Comment by OriHoch** [comment]
looks like a duplicate of #33 
@TheGrandVizier - what's the difference?

**Comment by TheGrandVizier** [comment]
Here is a list of filters we need to support:

    First name
    Last name (Exact, Starts with, Sounds like)
    Sex (Male, Female, Nevermind)
    Place of birth (Exact, Starts with, Sounds like)
    Place of marriage (Exact, Starts with, Sounds like)
    Place of death (Exact, Starts with, Sounds like)
    Year of birth (Exact, +/-1 year, +/-2 years, +/-3 years)
    Year of marriage (Exact, +/-1 year, +/-2 years, +/-3 years)
    Year of death (Exact, +/-1 year, +/-2 years, +/-3 years)
    Tree number

**Comment by TheGrandVizier** [comment]
Duplicate of #33
