### ISSUE TITLE
Duplicate and broken results in ftree search.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#12]
_From @TheGrandVizier on June 2, 2016 7:30_

Some results appear twice. The duplicate result,when clicked, produces a blank tree page.

Reproduce:
1. Search for the name "Magen".
2. Refine the search to tree 1181
3. Click each of the duplicate personas.

Result:
http://prntscr.com/b52kib

_Copied from original issue: Beit-Hatfutsot/dbs-front#44_

**Comment by TheGrandVizier** [comment]
Not fixed.
The second ofer still produces an empty tree view and a console-full of errors.

http://img.prntscr.com/img?url=http://i.imgur.com/Wjodt8W.png

**Comment by daonb** [comment]
Seems like the problem is related to persons that have no tree info. It's probably related to #20

**Comment by daonb** [comment]
seems like it's a good time to re-test.

**Comment by TheGrandVizier** [comment]
Not fixed.
There is still a blank for the second Dror Magen.
Once the working one is viewed, the first one also is viable via Recently Viewed.

**Comment by daonb** [comment]
It happens with:
http://test.dbs.bh.org.il/person/1181/0/I0241
and while it is a bug, it's been on the live server for quite some time : http://dbs.bh.org.il/person/1181/I0241

**Comment by nuritgazit** [comment]
@daonb meaning?

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-front #264](https://github.com/Beit-Hatfutsot/dbs-front/issues/264) via [**ZenHub**](https://www.zenhub.com/)
