### ISSUE TITLE
search results should contain geo data to support large map display on results page

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#120]
The map displayed on this result screen should display all relevant results that have coordinates.
The map will scale to fit them all in one view.

Frontned: https://github.com/Beit-Hatfutsot/dbs-front/issues/298

**Comment by OriHoch** [comment]
#### reproduction steps
* search for "Cohen"
* look at request to backend:
* http://api.dbs.bh.org.il/v1/search?from_=0&q=cohen
* make the request and look at the response

##### expected
* each result that have geo data should contain an attribute specifying it's coordinates
* the attribute should contain geo in expected format (TBD - which is the expected format?)

##### actual
* there are geo data on search results, but need to determine if it's in expected format or not
![image](https://cloud.githubusercontent.com/assets/1198854/23703016/7d258562-0406-11e7-87d9-82f66e2bcab3.png)

**Comment by Libisch** [comment]
Search result response does not contain the location data ("geometry"), which is included in all _Place_ item page responses, in the following format:

``` json
"geometry": {
  "type": "Point",
  "coordinates": [
      -3.0397259,
      33.986368
]
}
```

**Comment by Libisch** [comment]
(**Test** search results contain the geo data.)
