### ISSUE TITLE
Use Bagnowka images & data

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-back#130]
### **Overview:**
- Bagnowka stores thousands pre-war views of Poland and Eastern Europe from before 1945. BH has permission to scrape and add the data to our database. 
- All photos (and connected data) from [A-Z Galleries](http://www.bagnowka.pl/index.php?m=atoz) should be merged with BH DBS to be displayed as one of our collection.

### **Status:**
- We have a working scraping [script](https://github.com/Libisch/dbs-bagnowka-scrape), and the _data_ is stored in a json dataset.
- Tested uploading to AWS s3.

### **Next steps:**
- Upload images to usable storage and get new URLs.
- Update script and create a new dataset with valid image URLs.
- Convert the compete dataset to mach/use with API.

**Comment by Libisch** [comment]
@Beit-Hatfutsot/active-contributors

**Comment by OriHoch** [comment]
* for upload images I opened this issue (Beit-Hatfutsot/dbs-bagnowka-scrape#4) - for checking uploading to google storage (if it's simple it's worth to do rather then adding another provider)

**Comment by OriHoch** [comment]
* issue for researching how to match the bagnowka images json format to our mongo / elasticsearch document format - #131
* should have a script that scrapes the bagnowka images and writes them as photos/photoUnits to BH dbs - #132

**Comment by Libisch** [comment]
@TheGrandVizier @OriHoch 
Bagnowka is now added to ES via [pipelines](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/67), so this is not relevant, right?

**Comment by OriHoch** [comment]
issue is still relevant, but if it's done, feel free to close / move to QA
