### ISSUE TITLE
Shouldn't migrate items with status other than "completed".

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#140]
It seems during migration we also fetch items that are not under status "completed".
Such items then return 403 Forbidden.

Reproduce:
1. Search for Warsaw
2. Select the first relevant result (http://dbs.bh.org.il/place/warszawa-warsaw)

Expected result:
Arrive at Warsaw Item page

Actual Result:
403 Forbidden (http://prntscr.com/ergn6l)
Directly requesting it from API returns this:
`Forbidden

filter failed for {'Slug.En': u'place_warszawa-warsaw'} Status Description is not 'Completed'`

Notes:
I don't understand the merit of migrating things we cannot display. I think we would rather have an out-of-date item than 403.

**Comment by nuritgazit** [comment]
I think we can merge this item into this new one I've opened following an issue Haim and @OriHoch Ori discovered: https://github.com/Beit-Hatfutsot/dbs-front/issues/343

**Comment by OriHoch** [comment]
not sure if it's duplicated by #155 - but in any case, better to do it after or as part of the migration to Clearmash

**Comment by OriHoch** [comment]
shouldn't happen anymore in the new architecture

**Comment by TheGrandVizier** [comment]
Couldnt find any cases at present.
