### ISSUE TITLE
question: how should we handle items with missing header (in 1 or both languages)

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#142]
there are many items that are either missing a header in one language (e.g. have header in english but not in hebrew) or don't have a header at all

how should we handle these items?

#### possible options with rough story point estimates
* items with header in one language but not the other - 
  * don't show the items at all (for both languages) (**0.5**)
  * copy the header from one language to the other (**1.5**)
  * show the item only for the language which have the header (**3**)
* items without any header
  * don't show them at all (**0.5**)
* use a different logic to get the header (**∞**)
  * for example - use the first few words from the item text, or from other fields - need to investigate further.
  * might require different logic for different item types

**Comment by TheGrandVizier** [comment]
items with header in one language but not the other

**Comment by TheGrandVizier** [comment]
Also, anecdotal (no example):
In BHP, there are items that have identical headers for both languages. This may also mess with things.

**Comment by OriHoch** [comment]
Thanks @TheGrandVizier  - 

Please open issues for other sub-tasks and prioritize them (like if you want export of items without headers)

This is what I understood for expected logic, please approve:

### item with header in 1 language but not the other
##### expected
* no item page for the item in the language without header
* in search results - item appears but only links to the item in the language which have the header
  * it should appear with some message that we have item only in a different language
##### actual
* ?

### item without headers for both languages
##### expected
* no item page
* does not appear in search results
##### actual
* ?

**Comment by TheGrandVizier** [comment]
According to my examination, the situation you describe (missing both headers) does not exist.
Lets set up Mongo access and examine further.

**Comment by OriHoch** [comment]
@TheGrandVizier  - 
this is the logic after [dbs-back release 0.12.2](https://github.com/Beit-Hatfutsot/dbs-back/releases/tag/0.12.2) will be deployed:
* the ensure_required_metadatascript and the migration script - will ensure:
  * in elasticsearch only: items without header in 1 or both languages will get a header of `_`
* how it will work on search results and item page depends on frontend logic
  * from what I saw - frontend checks the UnitText of the item to decide if it's missing a language
  * it doesn't check the header
  * but - assuming item without header in language also doesn't have UnitText in a language - it will work OK.

Closing this issue for now, if you want you may open follow-up issue on frontend - to fix it's handling of these items (e.g. in case of item with `_` in header - link to item in the other language etc..)
