### ISSUE TITLE
Produce 'UnitId' for externally added items

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-back#147]
Files that are migrated from BHP have a `UnitId` field, which is a mandatory field. The `UnitId` number is generated by BHP, hence does not exist in docs from external sources. For external sources we need to generate an valid `UnitId`.

**Comment by Libisch** [comment]
@OriHoch 
To Consider:
- Not overriding existing UnitIds, including items that are not currently migrated (but maybe will be in the future).
- Should this number be created when generating the doc (following the scraping process), or should we have a stack of pre-prepared ready to use numbers that will be assigned when necessary?

**Comment by OriHoch** [comment]
worth to check first what it would take to have 2 fields identifying an item:
1. an item type (BHP or Bagnowka)
2. an item it (UnitId for BHP, other id for Bagnowka)

I guess it will require changes to the migration process and ensure_required_metadata script

Worth to check how hard it is, it might be just a few small changes

**Comment by OriHoch** [comment]
without doing this change - can try:
1. have negative UnitId - need to check if it's possible, this will ensure it's not used
2. add a very big number to each id - preventing clash with BHP UnitId

about the base id for each bagnowka item - can use the position of the item in the source json file

**Comment by Libisch** [comment]
- negative UnitId is unacceptable. 
- Assigning a very big number works, starting "11111111111"
