### ISSUE TITLE
Migrate Warsaw individually.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#158]
Currently on production warsaw returns a 403 and this needs to be fixed urgently and requires migration of a specific item.

Reproduce:
1.  http://dbs.bh.org.il/place/warszawa-warsaw

Result:
Receive 403, page does not load.

Solution:
Migrate specific item, Warsaw.

**Comment by OriHoch** [comment]
cannot migrate due to missing data files.. will update when solved

this is the command to run:
```bash
ssh bhs-infra
cd api
PYTHONPATH=. env/bin/python scripts/migrate.py -s 0 -i 73461 -c places
```

**Comment by OriHoch** [comment]
oh, looks like migrate worked even without the files.. :+1: 

warsaw is back
http://dbs.bh.org.il/place/warszawa-warsaw
