### ISSUE TITLE
Update scan of an item 

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#159]
_From @nuritgazit on April 26, 2017 13:51_

@OriHoch Haim is asking to display a new scan they added to for item ID 160561.
He also claims the current scan is flawed, you get a 403 error when trying to access it: 
http://dbs.bh.org.il/image/dora-and-leo-hamerman-new-jersey-usa-1987

This is for the donor of the image, so they are waiting for our update.

_Copied from original issue: Beit-Hatfutsot/dbs-front#350_

**Comment by TheGrandVizier** [comment]
_From @nuritgazit on May 1, 2017 5:30_

@OriHoch this is kind of urgent, would you be able to fix it soon?

**Comment by TheGrandVizier** [comment]
While we are at it, lets also migrate Warsaw.

**Comment by OriHoch** [comment]
currently I don't have access to BHP files, once I solve that I will be able to sync the image.. (it exists in BHP DB with correct permissions, so once we have access to the files it should work)

**Comment by OriHoch** [comment]
once there is access, this is the command to run:
```bash
ssh bhs-infra
cd api
PYTHONPATH=. env/bin/python scripts/migrate.py -s 0 -i 160561 -c photoUnits
```

**Comment by OriHoch** [comment]
done, item was synced
