### ISSUE TITLE
'All Results' in general search don't include 'person results'

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-back#160]
Search for "Einstaedter" family name with specified 'persons' collection:
http://devapi.dbs.bh.org.il/v1/search?q=Einstaedter&collection=persons
 returns 5 persons,
search with no collection:
http://devapi.dbs.bh.org.il/v1/search?q=Einstaedter
doesn't return any results

**Comment by OriHoch** [comment]
for general search results you need to add &with_persons=1 parameter to get person results:
http://devapi.dbs.bh.org.il/v1/search?q=Einstaedter&with_persons=1
