### ISSUE TITLE
DBS API - Free text linkify

### ISSUE THREAD

**Issue by nirgoldberg** [Beit-Hatfutsot/dbs-back#162]
Add the possibility to add links to DBS values within a given free text.

**Comment by nirgoldberg** [comment]
This becomes urgent in terms of budget of the G2G project, so I want to push it. @Libisch, can you handle?
@OriHoch, FYI and feedback

**Comment by Libisch** [comment]
@nirgoldberg I'm not sure I understand. Could you give an example (wanted/expected VS current)?

**Comment by OriHoch** [comment]
the description at the moment is not enough to start working on it, some design / tech-design is needed
(not saying @nirgoldberg should do this design, just that someone needs to do it..)

**Comment by Libisch** [comment]
@TheGrandVizier you'll take it from here?

**Comment by nuritgazit** [comment]
No. @nirgoldberg needs to define *his* needs, and we will find a solution to accommodate this need

**Comment by TheGrandVizier** [comment]
@nirgoldberg Waiting for you. Please hurry.

**Comment by nirgoldberg** [comment]
We need to implement an API towards DBS:
Input: HTML text block (no length limit)
Output: HTML text block, including integrated standard links to known terms within DBS.

I thought of such template to represent an integrated link:
<a href="{TERM LINK}" title="{TERM NAME}" data-image-src="{TERM FEATURED IMAGE}" data-excerpt="{TERM DESCRIPTION}" target="_blank">{TERM NAME}</a>

**Comment by Libisch** [comment]
@TheGrandVizier I think I know how to do it, might take a couple of days. Let me know what's the priority.

**Comment by OriHoch** [comment]
@Libisch I wrote some preliminary code in #190 - you can continue from there

**Comment by OriHoch** [comment]
### final implementation
* API receives a block of html (or text) and returns all the places / personalities / family names which appear in that text (title and url for each item)
* see the docs for example request / response: http://devapi.dbs.bh.org.il/v1/docs
* it supports GET method as well, but POST is preferred for long texts

**Comment by OriHoch** [comment]
merged in 0.13.4, deployed to test environment

* pay attention that the links it sends are for production environment, so just change the domain of the links you get to production if you want to test properly

**Comment by OriHoch** [comment]
example URL on test environment: http://devapi.dbs.bh.org.il/v1/linkify?html=hello%20from%20germany

**Comment by TheGrandVizier** [comment]
Example throws a bad gateway error

**Comment by OriHoch** [comment]
probably due to the move to the new infrastructure, will be handled in #212

**Comment by OriHoch** [comment]
fixed, works now, on dev environment

**Comment by TheGrandVizier** [comment]
This works, but it is unacceptably slow.
