### ISSUE TITLE
suggest api documentation: should indicate other collections, should indicate that only startswith works

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#168]
#### reproduction steps
* user would like to make API call to get suggestions for PhotoUnits
* look at suggest api documentation: http://devapi.dbs.bh.org.il/v1/docs#suggest

##### expected
* should see documentation that it's possible to do: `/v1/suggest/PhotoUnits/{input}`
  * could add a the collection as another param, like this: `/v1/suggest/{collection}/{input}`
* should see that only startswith suggestions work at the moment and phonetic / contains don't work - (AFAIK -- need to verify)

##### actual
* only possibilities in documentation are to suggest over all collections or over familyNames / places
  * no indication that it's possible to suggest for other collections (without the general suggest)
* no indication that only startswith works - user might try to use it

**Comment by Libisch** [comment]
@OriHoch 
- The description specifically indicates the startswith issue:
_Get suggestion of (...) DB titles in which the first characters match the user’s input(...)_
Should it be emphasized?
- As to phonetic/contains - me too, never saw results there.

**Comment by OriHoch** [comment]
yes, it should be emphasized, because currently the response contains also phonetic and contains - so it's confusing.. (need to verify first that indeed this is how it works - that really phonetic and contains will never have results)

**Comment by Libisch** [comment]
@TheGrandVizier Done. PR #172 approved and merged, changes visible [here](http://devapi.dbs.bh.org.il/v1/docs#suggest).

**Comment by OriHoch** [comment]
done, no need to test
