### ISSUE TITLE
[Task] run the deployment notes for 0.13.0 on test environment

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#169]
see the deployment notes for 0.13.0
https://github.com/Beit-Hatfutsot/dbs-back/releases/tag/0.13.0

need to run them on test environment

**Comment by Libisch** [comment]
Done. 
_**IMPORTANT NOTE:**_ Test environment now includes "Bagnowka" items, but the images are not visible yet. This should be salved by changing the way front reads the API response. Until then, the data would not be transferred to production environment.
