### ISSUE TITLE
General persons search: exact filter condition should be case insensitive

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-back#174]
### reproduction steps
* go to general search API  with the following params:
http://devapi.dbs.bh.org.il/v1/search?q=hoch&from_=0&collection=persons&first=Lea
(with param 'first=Lea') 
### Expected
* results for "Lea Hoch" 
### Actual 
* no results
### notes
* it works for the lower case version of the string: 'lea'
http://devapi.dbs.bh.org.il/v1/search?q=hoch&from_=0&collection=persons&first=lea

* However the 'old' person search returns the results for the both 'lea' and 'Lea':
http://devapi.dbs.bh.org.il/v1/person?first_name=lea&last_name=hoch

**Comment by OriHoch** [comment]
fixex, merged and hopefully deployed to test
