### ISSUE TITLE
ftree Notes field is limited and cannot contain entirety of some notes.

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#18]
@TheGrandVizier commented on [Thu Jun 02 2016](https://github.com/Beit-Hatfutsot/dbs-front/issues/45)

Some notes are very long.
The notes field in the ftree viewer is limited in size and cannot contain some of the lengthy notes left regarding some individuals in various tree.
Here is an example:

http://test.myjewishidentity.org/person/8888/I80530

---

@nuritgazit commented on [Tue Aug 30 2016](https://github.com/Beit-Hatfutsot/dbs-front/issues/45#issuecomment-243414918)

@daonb need to check if the db has the complete note. @Inna-r already checked that the API returns a truncated string.

---

@daonb commented on [Sun Sep 04 2016](https://github.com/Beit-Hatfutsot/dbs-front/issues/45#issuecomment-244594358)

It's a migration issue. The note field is truncated in the migration

**Comment by TheGrandVizier** [comment]
I am still trying to find a new case with oversized notes.

**Comment by TheGrandVizier** [comment]
Irrelevant with clearmash
