### ISSUE TITLE
persons advanced search API should support unified place field search param

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#180]
related frontend issue: beit-hatfutsot/dbs-front#411

### reproduction steps
* access search URL with place param, for example:
  * http://devapi.dbs.bh.org.il/v1/search?collection=persons&from_=0&q=anna+cohen&place=US&place_t=like

#### expected
* should return all persons which have "US" in any of their place fields

#### actual
* no place param - filter is ignored

#### notes
* relevant API documentation: http://devapi.dbs.bh.org.il/v1/docs#database-search-persons-advanced-search

**Comment by OriHoch** [comment]
#### implementation notes:
* tests/test_search.py: need to add a test-case for this scenario
* bhs_api/v1_endpoints.py: need to modify es_search function to handle the place param
  * it should use constants from bhs_api/persons.py file
  * it should do an elasticsearch query which would look something like this:
```
must_queries.append({"bool": {"should": [
    {"term": {"pob": "Paris"}},
    {"term": {"pom": "Paris"}},
    {"term": {"pod": "Paris"}}
]}})
```

**Comment by Libisch** [comment]
Done. See PR #182

**Comment by OriHoch** [comment]
deployed to test
