### ISSUE TITLE
general search persons - general search query should search in all person fields

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#181]
### preconditions
* person with last name "Cohen" and place of birth: "Moscow"
  * http://test.dbs.bh.org.il/person/7950/0/I252

### reproduction steps
* general search: http://test.dbs.bh.org.il/search
* type "Moscow" in search query -> ENTER
* click on "People"
* filter for last name "Cohen"
* search

#### expected
* should return the person
* API should search in all relevant text fields

#### actual
* no results
* this is because currently API searches only in first / last name fields

**Comment by OriHoch** [comment]
### implementation notes
* see notes on #180  - this is very similar

**Comment by Libisch** [comment]
Done. See #182

**Comment by OriHoch** [comment]
deployed to test
