### ISSUE TITLE
general search for "Germany" should return Germany as the first result

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#185]
### reproduction steps
* general search for "Germany" - http://test.dbs.bh.org.il/search?q=Germany

#### expected
* Germany place as the first result

#### actual
* Germany is on the 3rd row
* Got some persons from Germany before that
![image](https://user-images.githubusercontent.com/1198854/26920744-a23a1abe-4c42-11e7-9666-f53cde1ccfc1.png)

### notes
* the more general fix is to have results sorted by relevancy - maybe ElasticSearch can do something automatically / with some minor help from us

**Comment by Libisch** [comment]
@OriHoch When the query is general ("Germany" "Aviv" for that matter), how should it be decided from where to take the first result? should it be:
1. A perfect mach in Header (doesn't solve the problem for all cases)
2. Persons should always come after other collections (could return just as irrelevant results)
3. Take the first result from each collection (the *place* Germany would not necessarily return first)
4. ?

**Comment by OriHoch** [comment]
ElasticSearch has queries and functionality to help do that. generally, it works by assigning a score to each result

Yes, all your options might be used, or some combination of them

**Comment by OriHoch** [comment]
I think that simply setting ordering of collections in Elasticsearch will solve most common scenarios
e.g. priority between the collections

you can also, see that Elasticsearch already does ranking - when you search for "Germany" you see that all the first results have "Germany" in their title

**Comment by OriHoch** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

**Comment by TheGrandVizier** [comment]
I was under the impression we were already displaying results by relevance.
I don't know if this is a bug, more like a decision to avoid making a decision on our behalf.
Will discuss.

**Comment by TheGrandVizier** [comment]
@nuritgazit

**Comment by Libisch** [comment]
@OriHoch @TheGrandVizier 
To my understanding it is sorted by only by score (maybe the score for persons is higher because it's relative to other scores from persons result, not all results?).
<img width="748" alt="screen shot 2017-06-08 at 13 41 32" src="https://user-images.githubusercontent.com/20017334/26924996-b48b506c-4c50-11e7-8729-8fe27b006929.png">

**Comment by OriHoch** [comment]
@TheGrandVizier yes, we are showing results by relevancy, and I guess it worked fine before we added persons..
You can see, for example, that all results that have "Germany" in their title are shown first, before any results that have "Germany" in the UnitText

**Comment by OriHoch** [comment]
I opened a more general issue which we should work on - #186

closing this one
