### ISSUE TITLE
Missing status field in the PhotoUnits

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-back#194]
Some of our images Unauthorized to display at the web, although we don't have show this field to the users but we do need to determine if an image can be presented.
Need to understand which of this fields  can provide this data 
It can be in one of this fields:
DisplayStatusDesc or RightsCode or UnitDisplayStatus or ForDisplay or RightsDesc

**Comment by Libisch** [comment]
@Netush @TheGrandVizier There's an [open issue (#17)](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/17) regarding this and other restrictions.

**Comment by OriHoch** [comment]
closing as the field itself doesn't need to be shown

in the new pipelines we will not sync any documents that are not authorized for display (will be handled in Beit-Hatfutsot/mojp-dbs-pipelines#17)

so, I don't see a need to show these fields, feel free to re-open if you think we do need those fields
