### ISSUE TITLE
Missing fields in the places

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-back#195]
Places item should presented the user images attach (if have), need to be presented on a map - precise location & need to show related links if Editors put it manually. 
Need to understand which of this fields can provide all of this data
It might be in one of this fields:
**Images attach:**
Attachments or PrevPictureFileNames or PrevPicturePaths or PictureUnitsIds or Pictures
**Map coordinates:**
geometry.coordinates 
also might need PlaceParentTypeCodeDesc.En  & PlaceTypeCode & PlaceTypeDesc.En &  PlaceTypeDesc.He
(this data provide us what kind of a place is it - city / country / town...)
**Related:**
related

Also need to know the display status 
It can be in one of this fields:
DisplayStatusDesc or RightsCode or UnitDisplayStatus or ForDisplay or RightsDesc

**Comment by Libisch** [comment]
**Existing open issues for images:** 
1. [[Task] research how images should be handled from Clearmash #21](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/21)
2. [should get images data from clearmash api #24](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/24)
3. [sync should populate main_image_url and main_thumbnail_image_url fields #23](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/23)

**Existing open issue for Location:** 

[sync should add location field with lat/long #16](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/16)

This issue will be updated to include research - should we add geodata just for _Places_, or wherever possible (even if not for maps or current usage):
* Persons places (birth, marriage, death)
* PhotoUnits (if in title ot in related places, etc.)

**Comment by OriHoch** [comment]
closing this issue, as @Libisch wrote it is handled in other issues

feel free to re-open if you think there is something not handled / something is missing from the other issues
