### ISSUE TITLE
[Task] research - should Items have the their BHP id number?

### ISSUE THREAD

**Issue by Netush** [Beit-Hatfutsot/dbs-back#196]
Clearmash may have a different id number but a should have Additionally the BHP id number 

Examples:
**Photo unit:** "Beta Israel Woman Grinding Red Peppers, Wallaka, Ethiopia, 1984"	
BHP id number - 9995 - field: UnitId 
Clearmash id number - 184452 - field: item_id
**Place:** Tripoli, Libya
BHP id number - 72517 - field: UnitId 
Clearmash id number - 155036 - field: item_id

**Comment by Libisch** [comment]
@Netush why?

**Comment by Netush** [comment]
2 reasons:
One for the convenience of the people who work here especially in the Visual Documentation department
but the more important one is because people who donate us an image get this number & with this number they address us about those images

**Comment by Libisch** [comment]
@Netush 
@OriHoch correct me if I'm wrong - 
* To my understanding, the Visual Documentation department will work exclusively on Clearmesh, where the old BHP ID is available. Donors can also use the old ID when addressing the Visual Documentation department.
* The question is if we need this number for _online_ usage. donno.

**Comment by TheGrandVizier** [comment]
We need to have it just like BHP kept IDs from the system before it.
Whethet it has use for us is a good question.

**Comment by OriHoch** [comment]
@Libisch - I agree, also, don't see where it will be used online

also, considering that new Clearmash items probably won't have unit id, and that we also support items from multiple data sources - it doesn't make sense to keep data specific to a deprecated data source (BHP)

my understanding is that we will have 3 major data sources:

* old BHP items (now in clearmash) - which have BHP unit id
* new BHP items (created in clearmash) - which **don't** have BHP unit id
* items from other data sources (e.g. wikipedia) - which also **don't** have BHP unit id

however, if it's really needed, then need to see specifically where it is relevant when using the online databases site and how it will relate to the different data sources we now support

**Comment by nuritgazit** [comment]
Agreed, @OriHoch, the old number isn't relevant on site
