### ISSUE TITLE
should add support for the images field from pipelines

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#215]
after #76 is done, elasticsearch will provide `images` attribute which contains an array of image objects, something like this:

```json
[
  {"url": "www.url.to.big.image", "thumbnail_url": "www.url.to.thumbnail.image"},
  ...
]
```

## TO DO
* add this field to the index with proper mapping, once done - deploy the mojp-dbs-pipelines release
* return it for frontend (see Beit-Hatfutsot/dbs-front#449)

**Comment by OriHoch** [comment]
merged and deployed

now API responses for search and item will return the images array (if it exists in source data)

**Comment by OriHoch** [comment]
data was synced, it works - items have images now

**Comment by TheGrandVizier** [comment]
Yes they do.
