### ISSUE TITLE
DBS API probably has been changed and broke spotlight.bh.org.il/czech

### ISSUE THREAD

**Issue by nirgoldberg** [Beit-Hatfutsot/dbs-back#216]
DBS API URL as configured in spotlight project is: `http://api.dbs.bh.org.il/v1/collection/{location}`
It seems it has been changed in a way that broke the spotlight project.

In order to verify that, I've read the dbs data from a pre-stored file, rather than the API itself and it all looks fine.

**Comment by OriHoch** [comment]
I'm not familiar with this url and not sure what it's supposed to return

It seems to work correctly, not sure what you mean by broken if you could provide example of a specific url and the expected vs. actual outcome it would help

regarding the change we did - we just enforced https, but it does redirect when you access from http, so it should still work, even if you access the old url. You could try to change to https and see if that solves the problem.

**Comment by nirgoldberg** [comment]
I migrated spotlight to https (as part of my plan any way).
The API is just fine, the problem was related to another internal issue.
Thanks.
