### ISSUE TITLE
Revive the Migration

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#23]
run an internal process that every 5 minutes checks for the latest changes in the legacy CMS. For every update creates a task to update the mongo using celery, redis and the app server.
part of this issue is a new mongo server in GCE that is not part of a replication group.

**Comment by daonb** [comment]
New mongo & elastic search server is up - mongo1.

**Comment by TheGrandVizier** [comment]
To test this properly we need cooperation from Haim.
He needs to inform us when a change is made, to what item, and what the change is.
I will then be able to verify that this change is reflected on the live environment within 5 minutes.
I don't see another viable test that does not include Haim or his department.
@nuritgazit 

....Unless you are content with just going with it to prod "on good faith".

**Comment by nuritgazit** [comment]
@TheGrandVizier We don't need to bother Haim, we can ask Danna. She has an editor user and can change stuff (it's enough if she changes a letter from caps to non-caps, basically)

**Comment by TheGrandVizier** [comment]
Indeed.

**Comment by TheGrandVizier** [comment]
12181 was uploaded today, and is not found on test.dbs.bh.org.il person search.
@daonb

**Comment by TheGrandVizier** [comment]
Very much related bug:
https://github.com/Beit-Hatfutsot/dbs-back/issues/45
