### ISSUE TITLE
General search should search with "AND" operator instead of "OR". 

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#24]
The General search currently searches with "AND" and not "OR".
This causes a multitude of not-so-relevant results and a bit floody.

The higher powers demand this be changed and operator "OR" is used.

**Comment by daonb** [comment]
Seems like we need to pass a [default_operator](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-query-string-query.html) of `AND` when running queries
