### ISSUE TITLE
Related vs. General

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-back#29]
- Investigate Related mechanism. Consult with Pavel if needed
- Describe the hierarchy in General Search results (what are they ordered by)
- Find out of relevant results in Related also appear in General Search results

**Comment by daonb** [comment]
- Related is now only by editor input
- Results are ordered by their [relevancy](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html)
- ?
