### ISSUE TITLE
CJH results are not visible outside of the museum.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#32]
_From @TheGrandVizier on September 8, 2016 9:20_

Results from CJH are only visible through the museuems network.
Users from outside the museum will not see results from CJH.

This is problematic in many ways, mostly in terms of having two different experiences between museum and outside of it.

This brings forward another consideration. Perhaps it makes sense to show different things inside and outside, as it ties in to permissions / rights / museum - only stuff.

_Copied from original issue: Beit-Hatfutsot/dbs-front#195_

**Comment by TheGrandVizier** [comment]
_From @nuritgazit on October 19, 2016 10:58_

@daonb Can you please update on the reasons for this (old dump, etc.)?

**Comment by TheGrandVizier** [comment]
_From @nuritgazit on October 27, 2016 9:12_

@TheGrandVizier please move this issue to backend

**Comment by nuritgazit** [comment]
@TheGrandVizier I can see results from CJH on my mobile while using the mobile network (not a WiFi)

**Comment by TheGrandVizier** [comment]
Works outside of the museum now. Closing.
