### ISSUE TITLE
general search API should support searching on family trees

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#33]
#### reproduction steps
* open dbs website
* click on search
* search for "Moshe Cohen"
* look at the backend network request
* http://api.dbs.bh.org.il/v1/search?from_=0&q=Moshe+Cohen
  * **note** until frontend is changed to support persons, you have to add &with_persons=1 to get persons
* check the response of this request

##### expected
* response should include people named "Moshe Cohen" from the family trees

##### actual
* response does not include people
* currently family trees search uses a separate api

#### further filtering of the search results
* using the same search API url - add a collection parameter
* http://api.dbs.bh.org.il/v1/search?from_=0&q=Moshe+Cohen&collection=persons
  * **note** no need to add the with_persons query parameter here because you specifically request persons collection

##### expected
* response contains only people results (AKA family trees results)

#### filtering even further using specific people fields
* http://api.dbs.bh.org.il/v1/search?from_=0&q=Moshe+Cohen&collection=persons&first_name=moshe&last_name=cohen&place=tel+aviv
  * **note** see comment below for the list of supported query params

##### expected
* all results which match the query and the additional filters (first_name, last_name etc..)

###### original issue description
```
_From @TheGrandVizier on October 9, 2016 11:41_

The general search should be... General, and include search results from family trees that are a good match.
This brings up questions of performance, as it basically doubles the amount of entries to search, or possibly even more than doubles.
I feel that consolidating these under general search with a result-filter tab of family trees is the way to go.

_Copied from original issue: Beit-Hatfutsot/dbs-front#214_
```

**Comment by TheGrandVizier** [comment]
_From @nuritgazit on October 27, 2016 9:17_

@TheGrandVizier please move to backend

**Comment by OriHoch** [comment]
I'll do a technical design

**Comment by OriHoch** [comment]
tech design done - updated in issue description, @daonb @Inna-r - please review

**Comment by TheGrandVizier** [comment]
duplicate of #119

**Comment by TheGrandVizier** [comment]
Supported filters:

-     First name
-     Last name (Exact, Starts with, Sounds like)
-     Sex (Male, Female, Nevermind)
-     Place of birth (Exact, Starts with, Sounds like)
-     Place of marriage (Exact, Starts with, Sounds like)
-     Place of death (Exact, Starts with, Sounds like)
-     Year of birth (Exact, +/-1 year, +/-2 years, +/-3 years)
-     Year of marriage (Exact, +/-1 year, +/-2 years, +/-3 years)
-     Year of death (Exact, +/-1 year, +/-2 years, +/-3 years)
-     Tree number

**Comment by OriHoch** [comment]
API documentation and list of supported fields for searching are available here: 
http://devapi.dbs.bh.org.il/v1/docs#database-search-persons-advanced-search

**Comment by OriHoch** [comment]
deployed to test environment, see [0.12.3 release notes](https://github.com/Beit-Hatfutsot/dbs-back/releases/tag/0.12.3)
@TheGrandVizier - ready for testing, you can see the API documentation for details
@Inna-r - you can start using the API on test environment
