### ISSUE TITLE
Wizard Suggestions do not show clearly obvious variations.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#4]
_From @TheGrandVizier on June 2, 2016 12:42_

The suggestion box in the wizard behaves strangely.
In addition to not displaying "exact" matches, it also does not display quite prominent items.
Example:
typing Lev will not produce a suggestion for Levi or Levy, but will show Leviner.
Typing Mos will produce a suggestion for Moscow.

I suspect this is a leftover from the berger-kirschberger syndrome.

_Copied from original issue: Beit-Hatfutsot/dbs-front#81_

**Comment by daonb** [comment]
This is strange. The test server works well, the problem is only with the live API server.
Here's the result from test:
```
{"phonetic": ["Ben Labi", "Aben Labi", "Levi Ben Migas", "Levi Benshabbat", "Levi Ben Susan"],
 "contains": ["Azrilevitch", "Charleville", "Chaskelevitz", "Danialevich", "De Levie"],
  "starts_with": ["Levi", "Levi Ben Migas", "Levi Ben Safet", "Levi Ben Susan", "Levi Benshabbat"]}
```
And here is from the live:
```
{"phonetic": ["Ben Labi", "Aben Labi", "Levi Ben Migas", "Levi Benshabbat", "Levi Ben Susan"],
 "contains": ["Leviner", "Levi Ben Migas", "Ha-Levi Ibn Migas", "Levi-Azancot", "Ha-Levi-Valenci"],
  "starts_with": ["Leviner", "Levi Ben Migas", "Levi-Azancot", "Levi-Valensi", "Levi Benshabbat"]}
```

**Comment by daonb** [comment]
This raises an issue of how we order the results. If I use text search to look names similar to LEVI the top 5 results are: LEVI, LEVIE, LEVIES, LEVYS, LEVIS . This makes sense as they are the closest thing we have to LEVI.
So , we need to better define the order of the "starting with" and "contains" results as right now, it's left for chance.

**Comment by nuritgazit** [comment]
It looks like we will need to order by length - from the shortest to the longest.

**Comment by daonb** [comment]
I did some research and found out that our search engine - elasticsearch - has a special [completion suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-completion.html) which is built for the task.
I'm now working on integrating it and having it up on dev so we can play with it.

**Comment by daonb** [comment]
Deployed the new completion on dev. Phonetic is not there yet, but I did some performance measurements and the time to search for suggestion to `Cohen` went from 0.229 seconds to 0.014 .
