### ISSUE TITLE
Change Fork me on Github to this design

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/dbs-back#53]
http://tholman.com/github-corners/

(I'm sorry, but too many people have said it's weird / not to mention not nice)

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-front #244](https://github.com/Beit-Hatfutsot/dbs-front/issues/244) via [**ZenHub**](https://www.zenhub.com/)
