### ISSUE TITLE
Related appears twice if it is connected twice in BHP.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#54]
If a place is connected to a luminary in BHP by two different routes, for example, Activity place and death place, the related value will appear twice on the item-page on the DB site as well.

We hope this will be solved by clearMash.
If it isn't, perhaps a front end solution is in order.
Keeping in backened repo for now for documentation purposes.
This is more of an issue with BHP than with us - Death plays implies activity, no reason to connect twice.

**Comment by nuritgazit** [comment]
@OriHoch @TheGrandVizier considering clearmash, will we still need to fix this?

**Comment by OriHoch** [comment]
I don't know

**Comment by TheGrandVizier** [comment]
Irrelevant, closing.
