### ISSUE TITLE
Incorrect display of Item pages with no translation

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#55]
_From @TheGrandVizier on December 20, 2016 13:27_

Some items are displayed incorrectly, with numbers instead of their name appearing.
In this search:
http://test.dbs.bh.org.il/search?q=Munkacs&collection=places
There are 3 such items in this search. All of them exist in hebrew and have no english item pages, and they also do not display the message that they should: "This item page is not translated yet..."

If the ENG button is clicked while viewing the hebrew version, the URL does not change.
I suspect they have no slugs.

_Copied from original issue: Beit-Hatfutsot/dbs-front#246_

**Comment by daonb** [comment]
IMO, we should fix the content. According to [this search](http://test.dbs.bh.org.il/search?q=1234567890) we have 183 who are missing a title in one of the languages. Better we add the missing title to our content than support items with no title.

**Comment by nuritgazit** [comment]
@daonb, Danna is on it already

**Comment by TheGrandVizier** [comment]
Dana has changed several such items, but the amount of results on this page:
http://test.dbs.bh.org.il/search?q=1234567890
Stays the same.
IF the migration worked, it means the problem is deeper and different than what we thought it was.
Investigating.
@daonb
