### ISSUE TITLE
Handeling special characters in general search.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#6]
_From @TheGrandVizier on June 2, 2016 11:7_

Currently the handeling is not very well defined.
1. \ (backslash) makes a search run forever.
2. / causes an escape (%F) to be added to the search string.
3. No other special characters were found as disruptive so far.

_Copied from original issue: Beit-Hatfutsot/dbs-front#65_

**Comment by daonb** [comment]
I think `:` is also bad for you, but I don't want to fix this. The special characters gives the user super power, if he knows how to use them. For example searching [Header.En:/198[0-9]/](http://dbs.bh.org.il/search?q=Header.En:~2F198[0-9]~2F) will find all items that have a year from the 80s in their title.
There is a bug here, but it's a front-end bug. When you search using an illegal query the API server returns an error status code of  `400` and a message of "Invalid query parameter." that causes the client to hang.

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/dbs-front #241](https://github.com/Beit-Hatfutsot/dbs-front/issues/241) via [**ZenHub**](https://www.zenhub.com/)
