### ISSUE TITLE
Show all persons names (including middle and maiden names).

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#60]
Right now, if there is a middle name, it is not shown.
If there is a maiden name, it is shown instead of the last name.
We need to show the fullest variation of the name possible, as in BHP.

To do this: 
First name field to also filter through Middle names.
Last name field to also filter through Maiden names.

**Comment by TheGrandVizier** [comment]
From Haim:

הי ניקו,
 
אתה מתייחס לשתי בעיות שונות:
 
1.      שמות פרטיים מרוביים מופיעים בשדה אחד = שם פרטי.  החיפוש צריך להביא את כל השמות הרשומים בשדה זה, לא משנה איזה מהם חיפש היוזר..  על השדה הזה גם צריך להחיל את אופציות החיפוש הנוספות = נשמע כמו, מתחיל ב-.  כך אפשר לאתר אנשים שעליהם לא ידוע שם משפחה או לא רשום שם משפחה, אבל רשומים פרטים נוספים, למשל שם של מקום לידה או/ו פטירה.
 
2.      שם משפחה ושם נעורים רשומים בשדות שונים.  החיפוש, אם מתבצע על שני השדות בו זמנית, צריך להציג את התוצאות על פי מה שרשום במקור, דהיינו, שם משפחה כשם משפחה ושם נעורים כשם נעורים, ולא לערבב ביניהם. זה חשוב, כי במציאות ישנן עוד אפשרויות, כגון שמות משפחה כפולים ויותר, שמות רשומים בלועזית ובעברית בשדה אעחד, שמות קודמים רשומים בסוגריים ועוד.
 
אשמח לפרט.
 
תודה רבה

**Comment by TheGrandVizier** [comment]
1. Talk to Honza (benny)

**Comment by OriHoch** [comment]
following sprint planning we decided to keep this issue simple and not make any changes to migration process

this means that change will be only based on data we already have and just making sure we return consistent details back regarding names

**Comment by OriHoch** [comment]
#### reproduction steps
* open http://test.dbs.bh.org.il/person/1130/0/I4382
* notice that the full person name is displayed
* click on another person in the tree
* refresh the page (e.g. press Ctrl+F5)
* now click to go back to the person from original link

##### expected
* show the full person name

##### actual
* shows only the first name

**Comment by OriHoch** [comment]
@TheGrandVizier  - I added 1 example I found, please see if there are other scenarios

**Comment by OriHoch** [comment]
right now it seems like Beit-Hatfutsot/dbs-front#329 covers all the scenarios.. (including the one I wrote above)

@TheGrandVizier  - it is fixed and on test, if this is the only scenario you can close this issue
