### ISSUE TITLE
add /cm/callback for Clearmash API callback

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#72]
from [their doc](https://www.clearmash.com/skn/c7/Support/e1043/External_Resources_API__Server_API_):

> External resource can receive web requests on events in ClearMash. To register to a new evet you need to register it in the "Manage External Resource" screen (see ClearMash User Guide for more information).
>When the event is occurred ClearMash will send a web request with the event information to the registered URL.

**Comment by OriHoch** [comment]
will be handled in Beit-Hatfutsot/mojp-dbs-pipelines#53
