### ISSUE TITLE
Scrape some data into clearmash

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#74]

**Comment by nuritgazit** [comment]
Adding a batch Ivana harvested from this site for a trial.
Content is photos + data in excel. 

We need to understand how its best to be done (how document should look like, what to add/remove, would it work like this, etc.) before major data is harvested.  
[Excel on Drive](https://docs.google.com/spreadsheets/d/1uO_4yGwMpTGY1oegDA03Tyb2GiTRfhaW9m-s5PQk7YQ/edit?usp=sharing)
[Images on Drive](https://drive.google.com/open?id=0B6aHDT7jKnxkaXV3RGtmQ0pxd0k)

**Comment by nuritgazit** [comment]
Since Libi is doing the Bagnowka task, and Ori is working on Clearmash, this issue is no longer relevant and I'm closing it
