### ISSUE TITLE
Double results in general search follwoing full migration

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#79]
The general search displays doubled search results for any search, following a full migration.

Reproduce:
1. go to test.dbs.bh.org.il
2. use general search to search for Moscow

Result:
All results appear twice.

**Comment by OriHoch** [comment]
@TheGrandVizier - why was it closed? is it fixed and merged? tested? or just not needed anymore?

**Comment by TheGrandVizier** [comment]
It is an infra issue that effected both test and prod and thus was not
subject to normal flow.

Bug itself was a part of ongoing migration tweaks.

Sorted
