### ISSUE TITLE
Wrong coordiante for Gorki

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#80]
Apprently, the town of Gorki has been relocated to Ethiopia.
It is now located south of the capital city Adis Ababe.

http://dbs.bh.org.il/place/gorki

I'm assuming this is just an incorrect coordinate, or a place of similar name in Ethiopia.
Please check it out.

**Comment by Inna-r** [comment]
@TheGrandVizier Apparently it is Nizhny Novgorod  , From 1932 to 1990, it was known as Gorky (not Gorki), and it was and still  located in Russia, not Belarus. 
When i searched for 'Gorki' in openstreetmap, the Ethiopian Gorki was the first result i got. So the possible option to fix this is to change the item's title.

**Comment by TheGrandVizier** [comment]
Dumped coordinates system for now.
