### ISSUE TITLE
Some thumbnails on result cards are not displayed (403)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#81]
_From @TheGrandVizier on November 30, 2016 9:6_

Some thumbnails are not displayed on result card when using general search.
This is how it looks:
http://prntscr.com/ddjbo7

The missing images return a 403.
Reproduce:
1. Search for "The Rabbi of Bobowa"

_Copied from original issue: Beit-Hatfutsot/dbs-front#240_

**Comment by TheGrandVizier** [comment]
_From @Inna-r on January 23, 2017 9:56_

I did a bit of research - the thumbnails exist, but not public.
@daonb how could we change this?

**Comment by daonb** [comment]
added a job to run every Sunday at 2am to ensure all thumbnails are with public access. Here's the command:
`gsutil -m acl set -R -a public-read gs://bhs-thumbnails`
