### ISSUE TITLE
Person search by dates produce infinite loader

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#82]
Searching by date of birth / marriage / death produces an infinite loader.

Reproduce:
1. Go to http://test.dbs.bh.org.il/person
2, Search for all entries with date of birth 1953 +/-2

Result:
Infinite loader

Example search:
http://test.dbs.bh.org.il/person?birth_year=1953:2&more=1

**Comment by daonb** [comment]
@ori seems like I'm needed elsewhere. can you take this from me?

**Comment by OriHoch** [comment]
tested on production (dbs.bh.org.il/person?birth_year=1953:2&more=1), looks good
