### ISSUE TITLE
Write an Admin Guide

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-back#83]
Summarize all the requests we got from Haim and his team and write a guide covering the common scenarios.

**Comment by TheGrandVizier** [comment]
What is dis? @daonb

**Comment by daonb** [comment]
Issue moved to [Beit-Hatfutsot/beit-hatfutsot-devops #9](https://github.com/Beit-Hatfutsot/beit-hatfutsot-devops/issues/9) via [**ZenHub**](https://www.zenhub.com/)

**Comment by OriHoch** [comment]
https://github.com/Beit-Hatfutsot/dbs-back/blob/dev/docs/admin.md
