### ISSUE TITLE
Case where an item cannot be clicked via general

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#84]
_From @TheGrandVizier on January 3, 2017 8:44_

When searched in the General Search, this item cannot be clicked.

Repro:

1. Search for Georgia in general search.
2. Click the search result for Georgia.
Result:
The result is not clickable.

_Copied from original issue: Beit-Hatfutsot/dbs-front#259_

**Comment by TheGrandVizier** [comment]
Another item that falls in this category is Biel.

**Comment by TheGrandVizier** [comment]
_From @Inna-r on January 23, 2017 13:33_

@TheGrandVizier results for Georgia and Biel are actually clickable. Some other examples?

**Comment by daonb** [comment]
Sounds to me like a problem with the ES data. IMO, resetting the data solved the issue.

**Comment by TheGrandVizier** [comment]
This is still alive on production, @daonb @OriHoch

**Comment by OriHoch** [comment]
I'll have a look

**Comment by OriHoch** [comment]
I did a quick fix for this problem by generating slug on the fly in case it doesn't exist in elastic search results

this will fix it for this case, and also, in general I think it's a good idea to do it because maybe there are more cases like this.

For the long-term I opened an issue #128 - to add a script that will ensure correct slugs

**Comment by TheGrandVizier** [comment]
It is my understanding benny already has such script.
And yes, the effects are far reaching. Georgia and biel are just examples.

**Comment by OriHoch** [comment]
the short-term fix was deployed to production, it should fix all cases where elasticsearch doesn't have the slug but mongo has the slug..

@TheGrandVizier - please test and see if you can find more cases (I couldn't find any..)
