### ISSUE TITLE
Suggestion list is ordered backwards in Wizard

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#9]
_From @TheGrandVizier on June 2, 2016 13:8_

The suggestion list in the wizard is inverted. 
"Starts with" lists the longest entries and not the shortest ones.
A good test subject for wizard search in this case is "Berl" under the location field.

Repro:
1. Enter Wizard
2. Into the location field, input Berl
Result:
The suggestion box showed Berlin second, after a much longer "Berlichingen"

_Copied from original issue: Beit-Hatfutsot/dbs-front#87_

**Comment by daonb** [comment]
So, should it be ordered based on length? This will probably solve #4 and #15 as well

**Comment by nuritgazit** [comment]
Yes
